version: '3.7'

services:
  client:
    image: ./client
    restart: always
    ports:
      - "127.0.0.1:3000:3000"

  api:
    image: ./api
    restart: always
    ports:
      - "127.0.0.1:4000:4000"

  redis:
    image: mongo
    ports:
      - "127.0.0.1:27000:27117"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: support_wheel_user
      MONGO_INITDB_ROOT_PASSWORD: support_wheel_password
